// <auto-generated />
using System;
using CarRental.Infrastructure.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarRental.Infrastructure.Migrations
{
    [DbContext(typeof(CarRentalContext))]
    [Migration("20190825204458_IdentitySranje")]
    partial class IdentitySranje
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarRental.Model.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<int>("CarCategoryId");

                    b.Property<string>("Color");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("Mileage");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ModifiedAt");

                    b.Property<int>("ProductionYear");

                    b.HasKey("Id");

                    b.HasIndex("CarCategoryId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Audi",
                            CarCategoryId = 4,
                            Color = "Black",
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 934, DateTimeKind.Utc).AddTicks(5871),
                            IsDeleted = false,
                            Mileage = 10500,
                            Model = "A4",
                            ProductionYear = 2018
                        },
                        new
                        {
                            Id = 2,
                            Brand = "BMW",
                            CarCategoryId = 3,
                            Color = "Red",
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 934, DateTimeKind.Utc).AddTicks(7458),
                            IsDeleted = false,
                            Mileage = 100500,
                            Model = "320d",
                            ProductionYear = 2015
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Mazda",
                            CarCategoryId = 3,
                            Color = "Black",
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 934, DateTimeKind.Utc).AddTicks(7481),
                            IsDeleted = false,
                            Mileage = 12500,
                            Model = "3",
                            ProductionYear = 2014
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Audi",
                            CarCategoryId = 4,
                            Color = "Blue",
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 934, DateTimeKind.Utc).AddTicks(7481),
                            IsDeleted = false,
                            Mileage = 25500,
                            Model = "A7",
                            ProductionYear = 2018
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Mercedes",
                            CarCategoryId = 3,
                            Color = "Black",
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 934, DateTimeKind.Utc).AddTicks(7481),
                            IsDeleted = false,
                            Mileage = 150000,
                            Model = "c200",
                            ProductionYear = 2013
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Citroen",
                            CarCategoryId = 4,
                            Color = "Yellow",
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 934, DateTimeKind.Utc).AddTicks(7481),
                            IsDeleted = false,
                            Mileage = 107500,
                            Model = "c3",
                            ProductionYear = 2010
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Peugeot",
                            CarCategoryId = 3,
                            Color = "Red",
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 934, DateTimeKind.Utc).AddTicks(7481),
                            IsDeleted = false,
                            Mileage = 100500,
                            Model = "307",
                            ProductionYear = 2015
                        });
                });

            modelBuilder.Entity("CarRental.Model.Models.CarCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CarCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 936, DateTimeKind.Utc).AddTicks(2272),
                            IsDeleted = false,
                            Name = "van"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 936, DateTimeKind.Utc).AddTicks(2602),
                            IsDeleted = false,
                            Name = "mini-van"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 936, DateTimeKind.Utc).AddTicks(2607),
                            IsDeleted = false,
                            Name = "limousine"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 936, DateTimeKind.Utc).AddTicks(2607),
                            IsDeleted = false,
                            Name = "hatchback"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 936, DateTimeKind.Utc).AddTicks(2607),
                            IsDeleted = false,
                            Name = "coupe"
                        });
                });

            modelBuilder.Entity("CarRental.Model.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Zip")
                        .IsUnique();

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 936, DateTimeKind.Utc).AddTicks(8353),
                            IsDeleted = false,
                            Name = "Sisak",
                            Zip = "44000"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 936, DateTimeKind.Utc).AddTicks(8916),
                            IsDeleted = false,
                            Name = "Zagreb",
                            Zip = "10000"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 936, DateTimeKind.Utc).AddTicks(8922),
                            IsDeleted = false,
                            Name = "Velika Gorica",
                            Zip = "10410"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 936, DateTimeKind.Utc).AddTicks(8922),
                            IsDeleted = false,
                            Name = "Osijek",
                            Zip = "31000"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 936, DateTimeKind.Utc).AddTicks(8922),
                            IsDeleted = false,
                            Name = "Slavonski Brod",
                            Zip = "35000"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 936, DateTimeKind.Utc).AddTicks(8928),
                            IsDeleted = false,
                            Name = "Rijeka",
                            Zip = "51000"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 936, DateTimeKind.Utc).AddTicks(8928),
                            IsDeleted = false,
                            Name = "Varaždin",
                            Zip = "42000"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 936, DateTimeKind.Utc).AddTicks(8928),
                            IsDeleted = false,
                            Name = "Krapina",
                            Zip = "49000"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 936, DateTimeKind.Utc).AddTicks(8928),
                            IsDeleted = false,
                            Name = "Split",
                            Zip = "21000"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 936, DateTimeKind.Utc).AddTicks(8928),
                            IsDeleted = false,
                            Name = "Dubrovnik",
                            Zip = "20000"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 936, DateTimeKind.Utc).AddTicks(8928),
                            IsDeleted = false,
                            Name = "Trogir",
                            Zip = "21220"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 936, DateTimeKind.Utc).AddTicks(8928),
                            IsDeleted = false,
                            Name = "Šibenik",
                            Zip = "22000"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 936, DateTimeKind.Utc).AddTicks(8928),
                            IsDeleted = false,
                            Name = "Vukovar",
                            Zip = "32000"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 936, DateTimeKind.Utc).AddTicks(8973),
                            IsDeleted = false,
                            Name = "Vinkovci",
                            Zip = "37000"
                        });
                });

            modelBuilder.Entity("CarRental.Model.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 938, DateTimeKind.Utc).AddTicks(3867),
                            IsDeleted = false,
                            Name = "Vukovarska 4c"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 2,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 938, DateTimeKind.Utc).AddTicks(4436),
                            IsDeleted = false,
                            Name = "Zagrebačka 5"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 4,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 938, DateTimeKind.Utc).AddTicks(4441),
                            IsDeleted = false,
                            Name = "Petrova 5"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 3,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 938, DateTimeKind.Utc).AddTicks(4441),
                            IsDeleted = false,
                            Name = "Sisačka 13"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 7,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 938, DateTimeKind.Utc).AddTicks(4441),
                            IsDeleted = false,
                            Name = "Slavonska 4c"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 8,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 938, DateTimeKind.Utc).AddTicks(4447),
                            IsDeleted = false,
                            Name = "Petrinjska 4c"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 1,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 938, DateTimeKind.Utc).AddTicks(4447),
                            IsDeleted = false,
                            Name = "Vukovarska 15c"
                        });
                });

            modelBuilder.Entity("CarRental.Model.Models.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CustomerId");

                    b.Property<int>("DropOffLocationId");

                    b.Property<DateTime?>("EndDate")
                        .IsRequired();

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedAt");

                    b.Property<int>("PickUpLocationId");

                    b.Property<string>("Remarks");

                    b.Property<bool>("Reserved");

                    b.Property<DateTime?>("StartDate")
                        .IsRequired();

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("DropOffLocationId");

                    b.HasIndex("PickUpLocationId");

                    b.HasIndex("UserId");

                    b.ToTable("Rentals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 3,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 939, DateTimeKind.Utc).AddTicks(3953),
                            CustomerId = 3,
                            DropOffLocationId = 3,
                            EndDate = new DateTime(2015, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            PickUpLocationId = 2,
                            Remarks = "blah blah",
                            Reserved = true,
                            StartDate = new DateTime(2015, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CarId = 3,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 939, DateTimeKind.Utc).AddTicks(5996),
                            CustomerId = 5,
                            DropOffLocationId = 4,
                            EndDate = new DateTime(2016, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            PickUpLocationId = 1,
                            Remarks = "blah blah",
                            Reserved = true,
                            StartDate = new DateTime(2016, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CarId = 1,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 939, DateTimeKind.Utc).AddTicks(6024),
                            CustomerId = 6,
                            DropOffLocationId = 3,
                            EndDate = new DateTime(2018, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            PickUpLocationId = 1,
                            Remarks = "blah blah",
                            Reserved = true,
                            StartDate = new DateTime(2018, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CarId = 2,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 939, DateTimeKind.Utc).AddTicks(6024),
                            CustomerId = 2,
                            DropOffLocationId = 2,
                            EndDate = new DateTime(2019, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            PickUpLocationId = 1,
                            Remarks = "blah blah",
                            Reserved = true,
                            StartDate = new DateTime(2019, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CarId = 6,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 939, DateTimeKind.Utc).AddTicks(6024),
                            CustomerId = 2,
                            DropOffLocationId = 2,
                            EndDate = new DateTime(2019, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            PickUpLocationId = 1,
                            Remarks = "blah blah",
                            Reserved = true,
                            StartDate = new DateTime(2019, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CarId = 5,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 939, DateTimeKind.Utc).AddTicks(6064),
                            CustomerId = 2,
                            DropOffLocationId = 2,
                            EndDate = new DateTime(2019, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            PickUpLocationId = 1,
                            Remarks = "blah blah",
                            Reserved = true,
                            StartDate = new DateTime(2019, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CarId = 4,
                            CreatedAt = new DateTime(2019, 8, 25, 20, 44, 57, 939, DateTimeKind.Utc).AddTicks(6070),
                            CustomerId = 2,
                            DropOffLocationId = 2,
                            EndDate = new DateTime(2019, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            PickUpLocationId = 1,
                            Remarks = "blah blah",
                            Reserved = true,
                            StartDate = new DateTime(2019, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CarRental.Model.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<DateTime?>("DateOfBirth")
                        .IsRequired();

                    b.Property<string>("DrivingLicenceNumber")
                        .IsRequired()
                        .HasMaxLength(8);

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("DrivingLicenceNumber")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "5740c080-abd1-480b-9c93-e56a4723e47d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "92f10f7c-93d3-42c2-b5bb-034b91ba6d46",
                            DateOfBirth = new DateTime(1990, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrivingLicenceNumber = "11111111",
                            EmailConfirmed = false,
                            FirstName = "Ivan",
                            IsDeleted = false,
                            LastName = "Ivanovic",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "b7886cb7-c3ef-4eda-8a05-afaaf4923f1e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "11cf7363-c522-4602-84b7-5bf14907d26a",
                            DateOfBirth = new DateTime(1990, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrivingLicenceNumber = "22222222",
                            EmailConfirmed = false,
                            FirstName = "Marko",
                            IsDeleted = false,
                            LastName = "Marković",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "4f41703b-3e3e-4b5f-b831-e5c590dab7f3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bf828c55-a359-40d3-9cda-b5fcb6e2e42c",
                            DateOfBirth = new DateTime(1990, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrivingLicenceNumber = "33333333",
                            EmailConfirmed = false,
                            FirstName = "Josip",
                            IsDeleted = false,
                            LastName = "Josipović",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "7e706949-242b-4011-957f-03c49cd7043e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f403bc4d-0021-408a-9d85-61b0b76bc59b",
                            DateOfBirth = new DateTime(1990, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrivingLicenceNumber = "44444444",
                            EmailConfirmed = false,
                            FirstName = "Pero",
                            IsDeleted = false,
                            LastName = "Perić",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "87b85a23-8a94-4a62-b868-7b8038a14899",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d1d8a0b7-7495-4c02-94a4-d70772876270",
                            DateOfBirth = new DateTime(1990, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrivingLicenceNumber = "55555555",
                            EmailConfirmed = false,
                            FirstName = "Matko",
                            IsDeleted = false,
                            LastName = "Matković",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "3184cea3-079f-4c7a-95b7-b5125dc84c0e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c58f376d-643e-4647-88d5-0df91f1e87c4",
                            DateOfBirth = new DateTime(1990, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrivingLicenceNumber = "88888888",
                            EmailConfirmed = false,
                            FirstName = "Ivica",
                            IsDeleted = false,
                            LastName = "Ivić",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "e3971387-4830-42c8-801f-fa4bc3854a89",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b9ebfb1d-8f10-4336-b919-1dfd8ccc38a9",
                            DateOfBirth = new DateTime(1990, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrivingLicenceNumber = "99999999",
                            EmailConfirmed = false,
                            FirstName = "Davor",
                            IsDeleted = false,
                            LastName = "Davorić",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "b4ae978f-3feb-4dc6-a88b-5f5544aa882e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2d5abf96-3765-4a5f-8765-66d41f167bff",
                            DateOfBirth = new DateTime(1990, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrivingLicenceNumber = "12121212",
                            EmailConfirmed = false,
                            FirstName = "Dario",
                            IsDeleted = false,
                            LastName = "Dariović",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "83dfe8c8-afdc-4a75-a658-fd06fca5127e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9b9163f7-ce90-4c83-8f9b-0580c3ea4ca1",
                            DateOfBirth = new DateTime(1990, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrivingLicenceNumber = "12312312",
                            EmailConfirmed = false,
                            FirstName = "Dorian",
                            IsDeleted = false,
                            LastName = "Dorianović",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("CarRental.Model.Models.Car", b =>
                {
                    b.HasOne("CarRental.Model.Models.CarCategory", "CarCategory")
                        .WithMany()
                        .HasForeignKey("CarCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CarRental.Model.Models.Location", b =>
                {
                    b.HasOne("CarRental.Model.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CarRental.Model.Models.Rental", b =>
                {
                    b.HasOne("CarRental.Model.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CarRental.Model.Models.Location", "DropOffLocation")
                        .WithMany()
                        .HasForeignKey("DropOffLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CarRental.Model.Models.Location", "PickUpLocation")
                        .WithMany()
                        .HasForeignKey("PickUpLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CarRental.Model.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CarRental.Model.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CarRental.Model.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CarRental.Model.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CarRental.Model.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
